apiVersion: v1
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: gs
      file_sd_configs:
      - files:
        - /etc/targets/targets.yaml
    - job_name: operator
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      static_configs:
       - targets: ['gs-prometheus-operator-controller-manager-metrics-service.gs-prometheus-operator-system:8443']
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus-sample
  name: prometheus-sample-config
  namespace: default

