# permissions for end users to edit prometheuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-editor-role
rules:
- apiGroups:
  - monitoring.giantswarm.io
  resources:
  - prometheuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.giantswarm.io
  resources:
  - prometheuses/status
  verbs:
  - get
