---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - configmaps/finalizers
  verbs:
  - update
- resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - services/finalizers
  verbs:
  - update
- resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - StatefulSet/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - StatefulSets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - StatefulSets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.giantswarm.io
  resources:
  - prometheuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.giantswarm.io
  resources:
  - prometheuses/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.giantswarm.io
  resources:
  - prometheuses/status
  verbs:
  - get
  - patch
  - update
