apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-sample
spec:
  image: 
    repository: prom/prometheus
    version: v2.24.1
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  volumeClaimTemplate:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
  targets:
  - targets:
    - localhost:9090
    labels:
      app: prometheus
      job: prometheus
  # - targets:
  #   - cert-manager.cert-manager:9402
  #   labels:
  #     app: cert-manager
  #     job: cert-manager
  additionalScrapeConfigs:
  - jobName: operator
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    staticConfigs:
    - targets: 
      - "gs-prometheus-operator-controller-manager-metrics-service.gs-prometheus-operator-system:8443"
