apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-sample
spec:
  image: 
    repository: prom/prometheus
    version: v2.30.1
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  volumeClaimTemplate:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
  targets:
  - targets:
    - gs-prometheus-operator:8080
    labels:
      app: gs-prometheus-operator
      job: gs-prometheus
  # - targets:
  #   - cert-manager.cert-manager:9402
  #   labels:
  #     app: cert-manager
  #     job: cert-manager
