apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  image: 
    repository: prom/prometheus
    version: v2.24.1
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 2Gi
  volumeClaimTemplate:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: standard
  targets:
  - targets:
    - gs-prometheus-operator:8080
    labels:
      app: gs-prometheus-operator
      job: gs-prometheus
