apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  image: 
    repository: prom/prometheus
    version: v2.24.1
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 2Gi
  volumeClaimTemplate:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: standard
  targets:
  - targets:
    - localhost:9090
    labels:
      app: prometheus
      job: prometheus
  additionalScrapeConfigs:
  - job_name: operator
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    static_configs:
      - targets: ['gs-prometheus-operator-controller-manager-metrics-service.gs-prometheus-operator-system:8443']