apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app.kubernetes.io/name: gs-prometheus
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |-
    # Scrape config 
    #
    scrape_configs:
     - job_name: 'gs'  # This is a default value, it is mandatory.
       file_sd_configs:
        - files:
          - /etc/targets/targets.yaml
     - job_name: operator
       scheme: https
       tls_config:
         insecure_skip_verify: true
       bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
       static_configs:
        - targets: ['gs-prometheus-operator-controller-manager-metrics-service.gs-prometheus-operator-system:8443']