apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app.kubernetes.io/name: gs-prometheus
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |-
    # Scrape config 
    #
    scrape_configs:
     - job_name: 'gs'  # This is a default value, it is mandatory.
       file_sd_configs:
        - files:
          - /etc/targets/targets.yaml
