kind: Service
apiVersion: v1
metadata:
  name: gs-prometheus
  labels:
    app.kubernetes.io/name: gs-prometheus
    app.kubernetes.io/component: prometheus
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: gs-prometheus
    app.kubernetes.io/component: prometheus